#!/usr/bin/env bash
# Entrypoint for the "host" container: boot spire-agent with the one-time join
# token, wait for the Workload API socket, then keep the container alive so the
# reference app can be run against it on demand.
set -euo pipefail

: "${JOIN_TOKEN:?JOIN_TOKEN is required (generated by spire/up.sh)}"
: "${SPIFFE_WORKLOAD_SOCKET:=/tmp/spire-agent/public/api.sock}"

mkdir -p "$(dirname "$SPIFFE_WORKLOAD_SOCKET")"

echo "[host] starting spire-agent ..."
# The join token attests this node to the server once; after that the agent
# persists its SVID and reuses it across restarts.
spire-agent run \
  -config /opt/spire/conf/agent/agent.conf \
  -joinToken "$JOIN_TOKEN" &

echo "[host] waiting for Workload API at $SPIFFE_WORKLOAD_SOCKET ..."
for _ in $(seq 1 60); do
  [ -S "$SPIFFE_WORKLOAD_SOCKET" ] && break
  sleep 0.5
done
if [ ! -S "$SPIFFE_WORKLOAD_SOCKET" ]; then
  echo "[host] FATAL: Workload API socket never appeared" >&2
  exit 1
fi

echo "[host] ready. Read a secret with:"
echo "       docker compose --project-directory . -f spire/docker-compose.yml exec host \\"
echo "         dotnet /app/bin/Release/net8.0/secret-consumer.dll"
exec tail -f /dev/null
