server {
    bind_address = "0.0.0.0"
    bind_port    = "8081"
    socket_path  = "/tmp/spire-server/private/api.sock"
    trust_domain = "example.org"
    data_dir     = "/opt/spire/.data/server"
    log_level    = "INFO"

    default_x509_svid_ttl = "@@X509_SVID_TTL@@"
    default_jwt_svid_ttl  = "@@JWT_SVID_TTL@@"
}

plugins {
    DataStore "sql" {
        plugin_data {
            database_type     = "sqlite3"
            connection_string = "/opt/spire/.data/server/datastore.sqlite3"
        }
    }

    NodeAttestor "join_token" {
        plugin_data {}
    }

    KeyManager "disk" {
        plugin_data {
            keys_path = "/opt/spire/.data/server/keys.json"
        }
    }
}

UpstreamAuthority "akeyless_upstream" {
    plugin_cmd = "/opt/spire/AkeylessUpstreamAuthority"
    plugin_data {
        akeyless_gateway_url  = "@@GATEWAY_FULL@@/api/v2"
        access_id             = "@@UPSTREAM_ACCESS_ID@@"
        access_key            = "@@UPSTREAM_ACCESS_KEY@@"
        pki_cert_issuer_name  = "@@UPSTREAM_CERT_ISSUER@@"
    }
}
