#!/usr/bin/env bash
# Bring up the SPIRE topology and register the workloads.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT"

if [ ! -f .env ]; then
  echo "ERROR: .env not found. Run:" >&2
  echo "  cp spire/spire.env.example .env" >&2
  echo "  # then set AKEYLESS_GATEWAY to your account gateway URL" >&2
  exit 1
fi
set -a; . ./.env; set +a

: "${SPIFFE_TRUST_DOMAIN:=example.org}"
: "${JWT_AUDIENCE:=akeyless}"
: "${X509_SVID_TTL:=1h}"
: "${JWT_SVID_TTL:=5m}"
: "${ACCESS_ID:?ACCESS_ID is required. Set the plugin access id in .env.}"
: "${ACCESS_KEY:=}"
UPSTREAM_CERT_ISSUER="${UPSTREAM_CERT_ISSUER:-/spiffe/demo/pki}"
SVID_STORE_TARGET_FOLDER="${SVID_STORE_TARGET_FOLDER:-/spiffe/demo/svid}"
GATEWAY="${AKEYLESS_GATEWAY%/}"

mkdir -p "$ROOT/spire/.data"

# Set or replace a variable in .env, keeping the file the single source of
# runtime values for compose.
upsert_env() { # $1 name, $2 value
  if grep -q "^$1=" .env; then
    sed -i.bak "s|^$1=.*|$1=$2|" .env && rm -f .env.bak
  else
    printf '%s=%s\n' "$1" "$2" >> .env
  fi
}

# Gateways behind a private CA: copy the CA bundle into the topology and
# generate a compose override that mounts it and sets SSL_CERT_FILE in both
# containers, which Go TLS (both plugins, the agent, and the app on Linux)
# uses instead of the system roots. Public-CA gateways leave
# GATEWAY_CA_BUNDLE unset and get an empty override, so nothing changes. The
# value deliberately does not go into .env: every script sources .env into
# its environment, and a container path in SSL_CERT_FILE would break their
# host-side curl calls.
CA_OVERRIDE="$ROOT/spire/.data/compose-ca.yml"
: > "$CA_OVERRIDE"
if [ -n "${GATEWAY_CA_BUNDLE:-}" ]; then
  if [ ! -f "$GATEWAY_CA_BUNDLE" ]; then
    echo "ERROR: GATEWAY_CA_BUNDLE=$GATEWAY_CA_BUNDLE not found." >&2
    exit 1
  fi
  cp "$GATEWAY_CA_BUNDLE" "$ROOT/spire/.data/gateway-ca.pem"
  cat > "$CA_OVERRIDE" <<'OVERRIDE'
# Generated by spire/up.sh when GATEWAY_CA_BUNDLE is set. Do not edit.
services:
  spire-server:
    environment:
      SSL_CERT_FILE: /etc/akeyless/gateway-ca.pem
    volumes:
      - ./spire/.data/gateway-ca.pem:/etc/akeyless/gateway-ca.pem:ro
  host:
    environment:
      SSL_CERT_FILE: /etc/akeyless/gateway-ca.pem
    volumes:
      - ./spire/.data/gateway-ca.pem:/etc/akeyless/gateway-ca.pem:ro
OVERRIDE
fi

# The UpstreamAuthority plugin signs SPIRE's intermediate CA with a PKI
# Certificate Issuer. An issuer in Private CA mode requires a classic key as
# its signer, and because it signs a CA it must itself be a CA with
# cert-signing key usage. Both objects are created here (idempotent).
SIGNER_KEY="${UPSTREAM_CERT_ISSUER}-signer-key"

# 200 means the item exists, 404 means it does not; any other response
# (gateway down, auth failure) aborts the run instead of being mistaken for
# "missing", which would turn the next create call into a confusing conflict.
item_exists() {
  code=$(curl -sS -o /dev/null -w '%{http_code}' -X POST "$GATEWAY/api/v2/describe-item" \
    -H "Content-Type: application/json" \
    -d "$(jq -cn --arg n "$1" --arg t "$AKEYLESS_TOKEN" '{name:$n, token:$t}')")
  case "$code" in
    200) return 0 ;;
    404) return 1 ;;
    *)   echo "ERROR: gateway returned HTTP $code probing $1." >&2; exit 1 ;;
  esac
}

echo "==> Creating CA signer key $SIGNER_KEY ..."
if item_exists "$SIGNER_KEY"; then
  echo "    (signer key already exists)"
else
  curl -fsS -X POST "$GATEWAY/api/v2/create-classic-key" \
    -H "Content-Type: application/json" \
    -d "$(jq -cn --arg n "$SIGNER_KEY" --arg t "$AKEYLESS_TOKEN" \
      '{name:$n, alg:"RSA2048", "generate-self-signed-certificate":true, "certificate-ttl":365, token:$t}')" >/dev/null
  echo "    created."
fi

# Issuer TTL in seconds (30 days); it must exceed the SPIRE CA TTL, which
# defaults to 24h. The signer key's self-signed root certificate above lasts
# 365 days.
echo "==> Creating PKI Certificate Issuer $UPSTREAM_CERT_ISSUER ..."
if item_exists "$UPSTREAM_CERT_ISSUER"; then
  echo "    (issuer already exists)"
else
  curl -fsS -X POST "$GATEWAY/api/v2/create-pki-cert-issuer" \
    -H "Content-Type: application/json" \
    -d "$(jq -cn \
      --arg name "$UPSTREAM_CERT_ISSUER" \
      --arg signer "$SIGNER_KEY" \
      --arg ttl "2592000" \
      --arg sans "spiffe://$SPIFFE_TRUST_DOMAIN,spiffe://$SPIFFE_TRUST_DOMAIN/*" \
      --arg t "$AKEYLESS_TOKEN" \
      '{name:$name, ttl:$ttl, "signer-key-name":$signer, "is-ca":true, "key-usage":"certsign,crlsign", "allowed-uri-sans":$sans, token:$t}')" >/dev/null
  echo "    created."
fi

sed -e "s|example.org|$SPIFFE_TRUST_DOMAIN|g" \
    -e "s|@@X509_SVID_TTL@@|$X509_SVID_TTL|" \
    -e "s|@@JWT_SVID_TTL@@|$JWT_SVID_TTL|" \
    -e "s|@@GATEWAY_FULL@@|$GATEWAY|" \
    -e "s|@@ACCESS_ID@@|$ACCESS_ID|" \
    -e "s|@@ACCESS_KEY@@|$ACCESS_KEY|" \
    -e "s|@@UPSTREAM_CERT_ISSUER@@|$UPSTREAM_CERT_ISSUER|" \
    "$ROOT/spire/server.conf" > "$ROOT/spire/.data/server.conf"
sed -e "s|example.org|$SPIFFE_TRUST_DOMAIN|g" \
    -e "s|@@GATEWAY_FULL@@|$GATEWAY|" \
    -e "s|@@ACCESS_ID@@|$ACCESS_ID|" \
    -e "s|@@ACCESS_KEY@@|$ACCESS_KEY|" \
    -e "s|@@SVID_STORE_TARGET_FOLDER@@|$SVID_STORE_TARGET_FOLDER|" \
    "$ROOT/spire/agent.conf" > "$ROOT/spire/.data/agent.conf"

PARENT="spiffe://${SPIFFE_TRUST_DOMAIN}/agent/host"
DC="docker compose --project-directory $ROOT -f spire/docker-compose.yml -f spire/.data/compose-ca.yml"

echo "==> Starting spire-server ..."
$DC up -d --build spire-server

echo "==> Waiting for spire-server healthcheck ..."
for i in $(seq 1 60); do
  if $DC exec -T spire-server /opt/spire/bin/spire-server healthcheck \
        -socketPath /tmp/spire-server/private/api.sock >/dev/null 2>&1; then
    echo ' ok'; break
  fi
  printf '.'; sleep 1
  if [ "$i" -eq 60 ]; then
    echo; echo "ERROR: spire-server did not become healthy in 60s" >&2
    $DC logs --tail=30 spire-server >&2 || true
    exit 1
  fi
done

echo "==> Generating a one-time join token for the agent ..."
JOIN_TOKEN=$($DC exec -T spire-server /opt/spire/bin/spire-server token generate \
  -spiffeID "$PARENT" \
  -socketPath /tmp/spire-server/private/api.sock \
  | awk '/Token:/ {print $2}')
: "${JOIN_TOKEN:?failed to obtain join token}"

echo "==> Starting host (spire-agent + app) ..."
# Stash the one-time token in .env so compose injects it into the host service.
upsert_env JOIN_TOKEN "$JOIN_TOKEN"
# Use the pre-built host image from GHCR when available; build from source only
# as a fallback so first-time users skip the multi-minute local build.
if ! $DC pull host 2>/dev/null; then
  echo "    (pre-built image unavailable; building from source)"
  $DC build host
fi
$DC up -d host

echo "==> Waiting for the Workload API socket ..."
for i in $(seq 1 60); do
  if $DC exec -T host test -S /tmp/spire-agent/public/api.sock >/dev/null 2>&1; then
    echo ' ok'; break
  fi
  printf '.'; sleep 1
  if [ "$i" -eq 60 ]; then
    echo; echo "ERROR: Workload API socket never appeared" >&2
    $DC logs --tail=30 host >&2 || true
    exit 1
  fi
done

echo "==> Registering the workload ..."
"$SCRIPT_DIR/register-workload.sh"

echo "==> Registering the X.509-SVID workload with -storeSVID ..."
X509_SPIFFE_ID="spiffe://${SPIFFE_TRUST_DOMAIN}/sa/x509-workload"
if $DC exec -T spire-server /opt/spire/bin/spire-server entry show \
     -socketPath /tmp/spire-server/private/api.sock 2>/dev/null | grep -q "$X509_SPIFFE_ID"; then
  echo "    (X.509 workload already registered)"
else
  $DC exec -T spire-server /opt/spire/bin/spire-server entry create \
    -parentID "spiffe://${SPIFFE_TRUST_DOMAIN}/agent/host" \
    -spiffeID "$X509_SPIFFE_ID" \
    -selector "akeyless_secretsmanager:secretname:x509-workload-svid" \
    -storeSVID \
    -socketPath /tmp/spire-server/private/api.sock
fi

echo "==> Waiting for the Workload API to issue SVIDs ..."
for i in $(seq 1 30); do
  if $DC exec -T host spire-agent api fetch jwt -audience "$JWT_AUDIENCE" \
        -socketPath /tmp/spire-agent/public/api.sock -output json >/dev/null 2>&1; then
    echo ' ok'; break
  fi
  printf '.'; sleep 1
  if [ "$i" -eq 30 ]; then
    echo; echo "    WARN: not issuing SVIDs yet; rerun the app if the first call fails." >&2
  fi
done

cat <<EOF

==> SPIRE is up. Next steps:
  1. Wire Akeyless:   ./bootstrap/setup-akeyless.sh
  2. Read the secret: $DC exec -T host dotnet /app/bin/Release/net8.0/secret-consumer.dll
EOF
